"""create all tables

Revision ID: 14ec9d499ec3
Revises: 
Create Date: 2026-09-17 10:21:20.422800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '14ec9d499ec3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('stock', sa.Integer(), nullable=False))
    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=False))
    op.add_column('books', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'books', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'])
    op.drop_column('books', 'category')
    op.drop_column('books', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('books', sa.Column('category', mysql.VARCHAR(length=100), nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'books', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'category_id')
    op.drop_column('books', 'author_id')
    op.drop_column('books', 'stock')
    # ### end Alembic commands ###
